/**
 * Full Terms and Conditions Content
 * Edit this file to update the terms content
 */

import React from 'react';

export function TermsContent() {
  return (
    <div className="prose max-w-none pb-6
      prose-headings:font-bold prose-headings:text-gray-900 prose-headings:tracking-tight
      prose-h1:text-3xl prose-h1:mb-6 prose-h1:mt-10 prose-h1:pb-4 prose-h1:border-b-2 prose-h1:border-gray-200
      prose-h2:text-2xl prose-h2:mb-4 prose-h2:mt-10 prose-h2:font-semibold
      prose-h3:text-xl prose-h3:mb-3 prose-h3:mt-8 prose-h3:font-semibold
      prose-p:text-gray-700 prose-p:text-[15px] prose-p:leading-[1.75] prose-p:mb-5
      prose-strong:text-gray-900 prose-strong:font-semibold
      prose-ul:my-5 prose-ul:ml-6 prose-ul:space-y-2
      prose-ol:my-5 prose-ol:ml-6 prose-ol:space-y-2
      prose-li:text-gray-700 prose-li:text-[15px] prose-li:leading-[1.7]
      prose-a:text-blue-600 prose-a:font-medium prose-a:no-underline hover:prose-a:underline
      [&>*:first-child]:mt-0">

      <h1>Terms and Conditions</h1>

      <p><strong>Price IQ</strong> — Operated by Intrepix LLC</p>

      <p><em>Last Updated: 12/29/2025</em></p>

      <p>
        These Terms and Conditions ("Terms") govern access to and use of Price IQ, a cloud-based
        software platform that provides automated analytical tools for pricing analysis and decision
        support in connection with public-sector and government contracting opportunities (the "Services").
      </p>

      <p>
        Price IQ is owned and operated by Intrepix LLC, a Florida limited liability company ("Intrepix,"
        "Company," "we," or "us"). These Terms constitute a legally binding agreement between Intrepix
        and the individual or entity accessing or using the Services ("Customer," "you," or "your").
      </p>

      <p>
        By accessing or using Price IQ, you acknowledge that you have read, understood, and agree to be
        bound by these Terms. If you do not agree, you may not access or use the Services.
      </p>

      <h2>Important Notice Regarding Use</h2>

      <p>
        Price IQ is provided solely for commercial, governmental, and professional use. The Services are
        intended to support pricing analysis and decision-making processes but do not replace human judgment.
        All outputs generated by the Services are recommendations and analytical aids only and must be
        independently reviewed, validated, and approved by Customer prior to any submission to a government
        entity or third party.
      </p>

      <p>
        Price IQ does not certify pricing, does not ensure regulatory compliance, and does not submit
        proposals or pricing on Customer's behalf. Customer remains solely responsible for all pricing
        decisions, assumptions, compliance obligations, and submissions.
      </p>

      <h2>1. Eligibility and Business Use Only</h2>

      <h3>Business Use Only</h3>

      <p>
        The Services are intended solely for commercial, governmental, or professional use. The Services
        are not intended for personal, household, or consumer use.
      </p>

      <h3>Authority</h3>

      <p>
        You represent and warrant that you have the legal authority to enter into these Terms on behalf
        of yourself or the entity you represent.
      </p>

      <h2>2. Description of Services</h2>

      <h3>Decision-Support Software</h3>

      <p>
        The Services provide automated analytical tools intended to assist customers in reviewing
        solicitation documents and generating preliminary pricing analyses, pricing spreadsheets, and
        related outputs for government and public-sector procurements.
      </p>

      <h3>No Final Decision-Making</h3>

      <p>
        The Services do not determine final pricing, do not certify pricing accuracy, and do not replace
        human judgment. All outputs are recommendations and analytical aids only.
      </p>

      <h3>Human-in-the-Loop Requirement</h3>

      <p>
        Customer acknowledges and agrees that human review, validation, and approval are required prior
        to any submission of pricing or related materials to a government or third party.
      </p>

      <h2>3. Customer Responsibilities</h2>

      <h3>Compliance Responsibility</h3>

      <p>Customer is solely responsible for ensuring compliance with all applicable laws and regulations, including but not limited to:</p>

      <ul>
        <li>Federal Acquisition Regulation (FAR)</li>
        <li>Defense Federal Acquisition Regulation Supplement (DFARS)</li>
        <li>Truthful Cost or Pricing Data statutes and regulations (formerly TINA)</li>
        <li>Agency-specific procurement rules</li>
      </ul>

      <h3>No Certification</h3>

      <p>
        Intrepix does not certify, verify, or validate cost or pricing data and does not participate in
        negotiations with government entities.
      </p>

      <h3>Independent Verification</h3>

      <p>
        Customer is solely responsible for reviewing, validating, and verifying all outputs generated by
        the Services prior to use or submission.
      </p>

      <h2>4. Prohibited Data and Data Representations</h2>

      <h3>Prohibited Information</h3>

      <p>Customer shall not upload, store, or process through the Services any:</p>

      <ul>
        <li>Classified information</li>
        <li>ITAR-controlled data</li>
        <li>Export-controlled information</li>
        <li>Data requiring government authorization for processing</li>
        <li>Information subject to FedRAMP authorization requirements</li>
      </ul>

      <h3>CUI and Sensitive Information</h3>

      <p>
        The Services are not FedRAMP authorized. Customer is responsible for ensuring that any uploaded
        materials are appropriately sanitized and do not contain Controlled Unclassified Information (CUI)
        or similar sensitive data unless and until the Services are expressly authorized for such use.
      </p>

      <h3>Authority Representation</h3>

      <p>
        Customer represents and warrants that it has full legal authority to upload all data provided to
        the Services.
      </p>

      <h2>5. Data Ownership and Intellectual Property</h2>

      <h3>Customer Data Ownership</h3>

      <p>Customer retains all right, title, and interest in:</p>

      <ul>
        <li>Uploaded documents</li>
        <li>Generated pricing files</li>
        <li>Exported analyses and outputs</li>
      </ul>

      <h3>Platform IP</h3>

      <p>
        Intrepix retains all right, title, and interest in the Services, including all software,
        algorithms, models, workflows, and system logic.
      </p>

      <h3>Derived Insights</h3>

      <p>
        Intrepix may use anonymized and aggregated usage data that does not identify Customer or reveal
        Customer content for product improvement, analytics, and operational purposes.
      </p>

      <h2>6. AI and Output Disclaimers</h2>

      <h3>No Accuracy Guarantee</h3>

      <p>
        Outputs generated by the Services may be incomplete, inaccurate, or based on incorrect assumptions.
      </p>

      <h3>AI Limitations</h3>

      <p>
        Customer acknowledges that artificial intelligence systems may misinterpret documents, generate
        erroneous outputs, or fail to identify ambiguities.
      </p>

      <h3>No Professional Advice</h3>

      <p>
        The Services do not provide legal, accounting, pricing, procurement, or compliance advice.
      </p>

      <h2>7. Fees and Access</h2>

      <h3>Fees</h3>

      <p>
        Access to certain features may require payment of fees as specified in an applicable order or
        subscription plan.
      </p>

      <h3>Exports</h3>

      <p>Customer may export outputs in accordance with its subscription tier.</p>

      <h2>8. Security</h2>

      <h3>Security Measures</h3>

      <p>
        Intrepix implements commercially reasonable administrative, technical, and organizational
        safeguards to protect the Services.
      </p>

      <h3>No Compliance Warranty</h3>

      <p>
        Intrepix does not warrant compliance with NIST, FedRAMP, or other government security frameworks
        unless expressly stated in writing.
      </p>

      <h2>9. Termination and Suspension</h2>

      <h3>Suspension</h3>

      <p>
        Intrepix may immediately suspend access for suspected misuse, data violations, or security risks.
      </p>

      <h3>Termination</h3>

      <p>
        Either party may terminate for material breach following a reasonable notice and cure period,
        except where immediate termination is warranted due to legal or security risks.
      </p>

      <h2>10. Indemnification</h2>

      <h3>Customer Indemnification</h3>

      <p>Customer shall indemnify and hold harmless Intrepix from any claims arising out of:</p>

      <ul>
        <li>Use or misuse of the Services</li>
        <li>Submission of outputs to third parties or government entities</li>
        <li>Regulatory violations</li>
        <li>Upload of prohibited data</li>
      </ul>

      <h2>11. Limitation of Liability</h2>

      <h3>Exclusion of Damages</h3>

      <p>To the maximum extent permitted by law, Intrepix shall not be liable for:</p>

      <ul>
        <li>Lost contracts</li>
        <li>Lost profits or revenue</li>
        <li>Bid protests</li>
        <li>Government penalties or fines</li>
        <li>Indirect, incidental, or consequential damages</li>
      </ul>

      <h3>Liability Cap</h3>

      <p>
        Intrepix's total liability shall not exceed the fees paid by Customer in the twelve (12) months
        preceding the claim.
      </p>

      <h2>12. Force Majeure</h2>

      <p>
        Intrepix shall not be liable for failures caused by events beyond reasonable control, including
        government system outages, procurement platform failures, or regulatory changes.
      </p>

      <h2>13. Marketing and References</h2>

      <p>
        Customer may be referenced in anonymized metrics. Use of logos or customer names requires express
        written consent.
      </p>

      <h2>14. Governing Law and Venue</h2>

      <p>
        These Terms are governed by the laws of the State of New Jersey, without regard to conflict-of-law
        principles. Any disputes shall be resolved exclusively in the state or federal courts located in
        New Jersey. The parties waive any right to a jury trial.
      </p>

      <h2>15. General</h2>

      <h3>Entire Agreement</h3>

      <p>These Terms constitute the entire agreement between the parties.</p>

      <h3>Severability</h3>

      <p>If any provision is found unenforceable, the remainder shall remain in effect.</p>

      <h3>No Government Endorsement</h3>

      <p>Use of the Services does not imply government approval or endorsement.</p>

      <h2>Questions or Contact</h2>

      <p>
        <strong>Intrepix LLC</strong><br />
        <a href="mailto:service@priceiq.org">service@priceiq.org</a>
      </p>
    </div>
  );
}
